version: '2'

services:
    frontend:
        restart: always
        build: ./frontend
        ports:
            - "4200:4200"
        depends_on:
            - backend
        volumes:
            - ./frontend:/usr/src/app
        command: npm start

    backend:
        restart: always
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        links:
            - postgres:postgres
        volumes:
            - ./backend:/usr/src/app
        env_file: .env
        command: python manage.py runserver 0.0.0.0:8000

    postgres:
        restart: always
        image: postgres:9.6.6-alpine
        env_file: .env
        expose:
            - "5432"
        volumes:
            - forumapp-pgdata:/var/lib/postgresql/data/


volumes:
    forumapp-pgdata:
        external: true