version: '2'
services:
  backend:
    restart: always
    image: ./backend
    depends_on:
       - postgres
    links:
      - postgres:postgres
    volumes:
      - ./backend:/usr/src/app
      - /var/www/static:/var/www/static
    env_file: .env
    environment:
      - ALLOWED_HOST=ec2-52-201-245-26.compute-1.amazonaws.com
      - DEBUG=false
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn config.wsgi:application -w 3 -b :8000

  nginx:
    restart: always
    image: ./nginx
    volumes:
      - /var/www/html:/usr/share/nginx/html
      - /var/www/static:/var/www/static
    links:
      - backend:backend
    ports:
      - "80:80"

  postgres:
    restart: always
    image: postgres:9.6.6-alpine
    env_file: .env
    expose:
        - "5432"
    volumes:
        - forumapp-pgdata:/var/lib/postgresql/data/


volumes:
    forumapp-pgdata:
        external: true
